dist: trusty
sudo: false
language: node_js
node_js: 8.9.0
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.2.1
- export PATH=$HOME/.yarn/bin:$PATH
before_script:
- export DISPLAY=':99.0'
- sh -e /etc/init.d/xvfb start
cache:
  yarn: true
before_deploy:
- yarn global add npm-publish-prerelease
- echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
deploy:
  provider: script
  script: npm-publish-prerelease
  on:
    tags: true
env:
  global:
    secure: laAVYEAnDcj38MAXCZo1XUK8Bg6wjN+42H6ONFwM1teaCu9gKQxEsYqDprKDxV7pMlQorkL1L+C7Fror2fDC3HXVqHfVtO9qTWIJqoGndnHQkUqOZcb23bJO/j1A8JKkOkRJ+0XB3VRlJdbBx9kwQJvCDFjutZMTIOKX1InAJqrQxvC6M33n0HLuCaGOxIucFvpwheYf2zSEfG33IzMDkhzcAbG5b3Qdf905JsPZeCC3pfCPy+czj5rFB8zCRsgQ1IbWG3uI3Xbl6p5CnYHygZ78mSVpneRu0SGJ353fvOI1JerECZ9InMrB/y2JeGirHkz0r/+PQHiDGvlxCcsRmFwa8fJCrY4O3Zv2eZbcMjE93OG8KAHzzbzj+zQQ9ZAh5eep9cRYVPO1m1xNVQ9v/M5dMetohifRT/wck3I58u0Xslj/UvpkqbGQlBeNpGV1exWyZv+jZc5jGR1BepgRgiAxRAxQD2OWqyDtaVLhqSe4lyWucTUvjb4W7eQfeNT2PSN7PzsF0ASmAJQPK2e5rDGolaNKoXI9PzVO4PbeLlDY1j3N6E53hZ+xcYzlO8q/z2IywbtEWGS2EJ6y8sIvfJWjuS0uyIf5Jldt8pHP17CzpNUF6qjaJvTL6qPpSjninHVBVRw3CJ2blRaWsXy+7ASQ6oUFmPuCZu+iJUHDsl8=
